baseURL = "https://wwww.carlottastancampiano.it"
languageCode = "it"
defaultContentLanguage = "it"
title = "Carlotta Stancampiano"
theme = "hugo-coder"
googleAnalytics = ""
disqusShortname = ""
enableRobotsTXT =  true

[params]
brand = "Carlotta Stancampiano"
description = "Sono Carlotta Stancampiano un'Educatrice Prima Infanzia"
author = "Carlotta Stancampiano"
info = "Educatrice Prima Infanzia"
dateformat = "2 January 2006"
keywords = "Educatrice Prima Infanzia,Educatrice Prima Infanzia torino, Educatrice Prima Infanzia torino, educratice torino, insegnanti torino, torino"
facebook = "https://facebook.com/cstoduto"
twitter = "@claudiostoduto"
avatarurl = "images/foto.jpg"
favicon_32 = "images/fav.png"
favicon_16 = "images/fav.png"
footercontent = "Carlotta Stancampiano"
hidecredits = true
hidecopyright = false
rtl = false
math = true
images = ["/images/foto.jpg"]

[taxonomies]
  category = "categories"
  tag = "tags"

[params.publisher]
    name = "Carlotta Stancampiano"

    [params.publisher.logo]
      url = "/images/foto.jpg"
      width = 120
      height = 120

    [params.logo]
      url = "/images/foto.jpg"
      width = 120
      height = 120

    [params.image]
      url = "/images/foto.jpg"
      width = 600
      height = 600

[menu]
[[menu.main]]
    identifier = "Chi sono"
    name = "Chi sono"
    url = "/chi-sono/"
    weight = 1

[[menu.main]]
    name = "Blog"
    weight = 2.0
    url = "/blog/"

# Social links
[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin"
    weight = 6
    url = "https://www.linkedin.com/in/carlotta-stancampiano-45394821b/"
[[params.social]]
    name = "Podcast"
    icon = "fas fa-envelope"
    weight = 7
    url = "https://claudiostoduto.com/podcast"
