baseURL = "https://claudiostoduto.com"
languageCode = "it"
defaultContentLanguage = "it"
title = "Claudio Stoduto"
theme = "hugo-coder"
googleAnalytics = "UA-102432953-1"
disqusShortname = "claudiostoduto-com-2"
enableRobotsTXT =  true

[params]
brand = "Claudio Stoduto"
description = "Sono Claudio Stoduto un ex-giornalista, podcaster ed iPaddista con la passione per la tecnologia, l'informazione e la comunicazione."
author = "Claudio Stoduto"
info = "Ex giornalista. Podcaster."
dateformat = "2 January 2006"
keywords = "consulente digitale,consulente,blog,developer,personal,podcast,podcaster,tecnologia,sport,innovazione,tech,consulenza torino,consulente informatico,consulente digitale torino,consulente torino,web marketing torino, digital consultant torino"
facebook = "https://facebook.com/cstoduto"
twitter = "@claudiostoduto"
avatarurl = "images/foto.jpg"
favicon_32 = "images/fav.png"
favicon_16 = "images/fav.png"
footercontent = "Claudio Stoduto"
hidecredits = true
hidecopyright = false
rtl = false
math = true
images = ["/images/foto.jpg"]

[taxonomies]
  category = "categories"
  tag = "tags"

[params.publisher]
    name = "Claudio Stoduto"

    [params.publisher.logo]
      url = "/images/foto.jpg"
      width = 120
      height = 120

    [params.logo]
      url = "/images/foto.jpg"
      width = 120
      height = 120

    [params.image]
      url = "/images/foto.jpg"
      width = 600
      height = 600

[menu]
[[menu.main]]
    identifier = "Chi sono"
    name = "Chi sono"
    url = "/chi-sono/"
    weight = 1

[[menu.main]]
    name = "Blog"
    weight = 2.0
    url = "/progetti/"

    
[[menu.main]]
    name = "Newsletter"
    weight = 3.0
    url = "/newsletter/"


# Social links
[[params.social]]
    name = "Telegram"
    icon = "fab fa-telegram"
    weight = 6
    url = "https://t.me/ilrompiscatole"
[[params.social]]
    name = "Podcast"
    icon = "fas fa-podcast"
    weight = 7
    url = "https://claudiostoduto.com/podcast"
[[params.social]]
    name = "Libri"
    icon = "fas fa-book"
    weight = 9
    url = "https://claudiostoduto.com/libreria"
[[params.social]]
    name = "iPaddista"
    icon = "fas fa-tablet-alt"
    weight = 9
    url = "https://claudiostoduto.com/ipaddista"
[[params.social]]
    name = "Allenamenti"
    icon = "fas fa-dumbbell"
    weight = 10 
    url = "https://claudiostoduto.com/categories/allenamenti/"
    